/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UniformsRouteImport } from './routes/uniforms'
import { Route as TransportRoutesRouteImport } from './routes/transport-routes'
import { Route as TransportListRouteImport } from './routes/transport-list'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentParentsRouteImport } from './routes/student-parents'
import { Route as StudentListRouteImport } from './routes/student-list'
import { Route as StaffPointsRouteImport } from './routes/staff-points'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalaryPaymentsRouteImport } from './routes/salary-payments'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ReportCardsRouteImport } from './routes/report-cards'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as LibraryBooksRouteImport } from './routes/library-books'
import { Route as IdcardStudentsRouteImport } from './routes/idcard-students'
import { Route as IdcardStaffRouteImport } from './routes/idcard-staff'
import { Route as IdcardDriversRouteImport } from './routes/idcard-drivers'
import { Route as IdcardDesignerRouteImport } from './routes/idcard-designer'
import { Route as IdCardsRouteImport } from './routes/id-cards'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ExamResultsRouteImport } from './routes/exam-results'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as DisciplineRouteImport } from './routes/discipline'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as BookLoansHistoryRouteImport } from './routes/book-loans-history'
import { Route as BookLoansRouteImport } from './routes/book-loans'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AcademicYearsRouteImport } from './routes/academic-years'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UniformsRoute = UniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoutesRoute = TransportRoutesRouteImport.update({
  id: '/transport-routes',
  path: '/transport-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportListRoute = TransportListRouteImport.update({
  id: '/transport-list',
  path: '/transport-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentParentsRoute = StudentParentsRouteImport.update({
  id: '/student-parents',
  path: '/student-parents',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentListRoute = StudentListRouteImport.update({
  id: '/student-list',
  path: '/student-list',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPointsRoute = StaffPointsRouteImport.update({
  id: '/staff-points',
  path: '/staff-points',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryPaymentsRoute = SalaryPaymentsRouteImport.update({
  id: '/salary-payments',
  path: '/salary-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCardsRoute = ReportCardsRouteImport.update({
  id: '/report-cards',
  path: '/report-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryBooksRoute = LibraryBooksRouteImport.update({
  id: '/library-books',
  path: '/library-books',
  getParentRoute: () => rootRouteImport,
} as any)
const IdcardStudentsRoute = IdcardStudentsRouteImport.update({
  id: '/idcard-students',
  path: '/idcard-students',
  getParentRoute: () => rootRouteImport,
} as any)
const IdcardStaffRoute = IdcardStaffRouteImport.update({
  id: '/idcard-staff',
  path: '/idcard-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const IdcardDriversRoute = IdcardDriversRouteImport.update({
  id: '/idcard-drivers',
  path: '/idcard-drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const IdcardDesignerRoute = IdcardDesignerRouteImport.update({
  id: '/idcard-designer',
  path: '/idcard-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const IdCardsRoute = IdCardsRouteImport.update({
  id: '/id-cards',
  path: '/id-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamResultsRoute = ExamResultsRouteImport.update({
  id: '/exam-results',
  path: '/exam-results',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const BookLoansHistoryRoute = BookLoansHistoryRouteImport.update({
  id: '/book-loans-history',
  path: '/book-loans-history',
  getParentRoute: () => rootRouteImport,
} as any)
const BookLoansRoute = BookLoansRouteImport.update({
  id: '/book-loans',
  path: '/book-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicYearsRoute = AcademicYearsRouteImport.update({
  id: '/academic-years',
  path: '/academic-years',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-years': typeof AcademicYearsRoute
  '/accounting': typeof AccountingRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/book-loans': typeof BookLoansRoute
  '/book-loans-history': typeof BookLoansHistoryRoute
  '/classes': typeof ClassesRoute
  '/discipline': typeof DisciplineRoute
  '/discounts': typeof DiscountsRoute
  '/events': typeof EventsRoute
  '/exam-results': typeof ExamResultsRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/health': typeof HealthRoute
  '/id-cards': typeof IdCardsRoute
  '/idcard-designer': typeof IdcardDesignerRoute
  '/idcard-drivers': typeof IdcardDriversRoute
  '/idcard-staff': typeof IdcardStaffRoute
  '/idcard-students': typeof IdcardStudentsRoute
  '/library-books': typeof LibraryBooksRoute
  '/parents': typeof ParentsRoute
  '/payments': typeof PaymentsRoute
  '/report-cards': typeof ReportCardsRoute
  '/revenue': typeof RevenueRoute
  '/salary-payments': typeof SalaryPaymentsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/staff-points': typeof StaffPointsRoute
  '/student-list': typeof StudentListRoute
  '/student-parents': typeof StudentParentsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/teachers': typeof TeachersRoute
  '/transport-list': typeof TransportListRoute
  '/transport-routes': typeof TransportRoutesRoute
  '/uniforms': typeof UniformsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-years': typeof AcademicYearsRoute
  '/accounting': typeof AccountingRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/book-loans': typeof BookLoansRoute
  '/book-loans-history': typeof BookLoansHistoryRoute
  '/classes': typeof ClassesRoute
  '/discipline': typeof DisciplineRoute
  '/discounts': typeof DiscountsRoute
  '/events': typeof EventsRoute
  '/exam-results': typeof ExamResultsRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/health': typeof HealthRoute
  '/id-cards': typeof IdCardsRoute
  '/idcard-designer': typeof IdcardDesignerRoute
  '/idcard-drivers': typeof IdcardDriversRoute
  '/idcard-staff': typeof IdcardStaffRoute
  '/idcard-students': typeof IdcardStudentsRoute
  '/library-books': typeof LibraryBooksRoute
  '/parents': typeof ParentsRoute
  '/payments': typeof PaymentsRoute
  '/report-cards': typeof ReportCardsRoute
  '/revenue': typeof RevenueRoute
  '/salary-payments': typeof SalaryPaymentsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/staff-points': typeof StaffPointsRoute
  '/student-list': typeof StudentListRoute
  '/student-parents': typeof StudentParentsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/teachers': typeof TeachersRoute
  '/transport-list': typeof TransportListRoute
  '/transport-routes': typeof TransportRoutesRoute
  '/uniforms': typeof UniformsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-years': typeof AcademicYearsRoute
  '/accounting': typeof AccountingRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/book-loans': typeof BookLoansRoute
  '/book-loans-history': typeof BookLoansHistoryRoute
  '/classes': typeof ClassesRoute
  '/discipline': typeof DisciplineRoute
  '/discounts': typeof DiscountsRoute
  '/events': typeof EventsRoute
  '/exam-results': typeof ExamResultsRoute
  '/exams': typeof ExamsRoute
  '/expenses': typeof ExpensesRoute
  '/health': typeof HealthRoute
  '/id-cards': typeof IdCardsRoute
  '/idcard-designer': typeof IdcardDesignerRoute
  '/idcard-drivers': typeof IdcardDriversRoute
  '/idcard-staff': typeof IdcardStaffRoute
  '/idcard-students': typeof IdcardStudentsRoute
  '/library-books': typeof LibraryBooksRoute
  '/parents': typeof ParentsRoute
  '/payments': typeof PaymentsRoute
  '/report-cards': typeof ReportCardsRoute
  '/revenue': typeof RevenueRoute
  '/salary-payments': typeof SalaryPaymentsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/staff-points': typeof StaffPointsRoute
  '/student-list': typeof StudentListRoute
  '/student-parents': typeof StudentParentsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/teachers': typeof TeachersRoute
  '/transport-list': typeof TransportListRoute
  '/transport-routes': typeof TransportRoutesRoute
  '/uniforms': typeof UniformsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-years'
    | '/accounting'
    | '/announcements'
    | '/attendance'
    | '/auth'
    | '/book-loans'
    | '/book-loans-history'
    | '/classes'
    | '/discipline'
    | '/discounts'
    | '/events'
    | '/exam-results'
    | '/exams'
    | '/expenses'
    | '/health'
    | '/id-cards'
    | '/idcard-designer'
    | '/idcard-drivers'
    | '/idcard-staff'
    | '/idcard-students'
    | '/library-books'
    | '/parents'
    | '/payments'
    | '/report-cards'
    | '/revenue'
    | '/salary-payments'
    | '/settings'
    | '/staff'
    | '/staff-points'
    | '/student-list'
    | '/student-parents'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/transport-list'
    | '/transport-routes'
    | '/uniforms'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-years'
    | '/accounting'
    | '/announcements'
    | '/attendance'
    | '/auth'
    | '/book-loans'
    | '/book-loans-history'
    | '/classes'
    | '/discipline'
    | '/discounts'
    | '/events'
    | '/exam-results'
    | '/exams'
    | '/expenses'
    | '/health'
    | '/id-cards'
    | '/idcard-designer'
    | '/idcard-drivers'
    | '/idcard-staff'
    | '/idcard-students'
    | '/library-books'
    | '/parents'
    | '/payments'
    | '/report-cards'
    | '/revenue'
    | '/salary-payments'
    | '/settings'
    | '/staff'
    | '/staff-points'
    | '/student-list'
    | '/student-parents'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/transport-list'
    | '/transport-routes'
    | '/uniforms'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/academic-years'
    | '/accounting'
    | '/announcements'
    | '/attendance'
    | '/auth'
    | '/book-loans'
    | '/book-loans-history'
    | '/classes'
    | '/discipline'
    | '/discounts'
    | '/events'
    | '/exam-results'
    | '/exams'
    | '/expenses'
    | '/health'
    | '/id-cards'
    | '/idcard-designer'
    | '/idcard-drivers'
    | '/idcard-staff'
    | '/idcard-students'
    | '/library-books'
    | '/parents'
    | '/payments'
    | '/report-cards'
    | '/revenue'
    | '/salary-payments'
    | '/settings'
    | '/staff'
    | '/staff-points'
    | '/student-list'
    | '/student-parents'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/transport-list'
    | '/transport-routes'
    | '/uniforms'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicYearsRoute: typeof AcademicYearsRoute
  AccountingRoute: typeof AccountingRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  BookLoansRoute: typeof BookLoansRoute
  BookLoansHistoryRoute: typeof BookLoansHistoryRoute
  ClassesRoute: typeof ClassesRoute
  DisciplineRoute: typeof DisciplineRoute
  DiscountsRoute: typeof DiscountsRoute
  EventsRoute: typeof EventsRoute
  ExamResultsRoute: typeof ExamResultsRoute
  ExamsRoute: typeof ExamsRoute
  ExpensesRoute: typeof ExpensesRoute
  HealthRoute: typeof HealthRoute
  IdCardsRoute: typeof IdCardsRoute
  IdcardDesignerRoute: typeof IdcardDesignerRoute
  IdcardDriversRoute: typeof IdcardDriversRoute
  IdcardStaffRoute: typeof IdcardStaffRoute
  IdcardStudentsRoute: typeof IdcardStudentsRoute
  LibraryBooksRoute: typeof LibraryBooksRoute
  ParentsRoute: typeof ParentsRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportCardsRoute: typeof ReportCardsRoute
  RevenueRoute: typeof RevenueRoute
  SalaryPaymentsRoute: typeof SalaryPaymentsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StaffPointsRoute: typeof StaffPointsRoute
  StudentListRoute: typeof StudentListRoute
  StudentParentsRoute: typeof StudentParentsRoute
  StudentsRoute: typeof StudentsRoute
  SubjectsRoute: typeof SubjectsRoute
  TeachersRoute: typeof TeachersRoute
  TransportListRoute: typeof TransportListRoute
  TransportRoutesRoute: typeof TransportRoutesRoute
  UniformsRoute: typeof UniformsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uniforms': {
      id: '/uniforms'
      path: '/uniforms'
      fullPath: '/uniforms'
      preLoaderRoute: typeof UniformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-routes': {
      id: '/transport-routes'
      path: '/transport-routes'
      fullPath: '/transport-routes'
      preLoaderRoute: typeof TransportRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-list': {
      id: '/transport-list'
      path: '/transport-list'
      fullPath: '/transport-list'
      preLoaderRoute: typeof TransportListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-parents': {
      id: '/student-parents'
      path: '/student-parents'
      fullPath: '/student-parents'
      preLoaderRoute: typeof StudentParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-list': {
      id: '/student-list'
      path: '/student-list'
      fullPath: '/student-list'
      preLoaderRoute: typeof StudentListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-points': {
      id: '/staff-points'
      path: '/staff-points'
      fullPath: '/staff-points'
      preLoaderRoute: typeof StaffPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-payments': {
      id: '/salary-payments'
      path: '/salary-payments'
      fullPath: '/salary-payments'
      preLoaderRoute: typeof SalaryPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-cards': {
      id: '/report-cards'
      path: '/report-cards'
      fullPath: '/report-cards'
      preLoaderRoute: typeof ReportCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-books': {
      id: '/library-books'
      path: '/library-books'
      fullPath: '/library-books'
      preLoaderRoute: typeof LibraryBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idcard-students': {
      id: '/idcard-students'
      path: '/idcard-students'
      fullPath: '/idcard-students'
      preLoaderRoute: typeof IdcardStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idcard-staff': {
      id: '/idcard-staff'
      path: '/idcard-staff'
      fullPath: '/idcard-staff'
      preLoaderRoute: typeof IdcardStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idcard-drivers': {
      id: '/idcard-drivers'
      path: '/idcard-drivers'
      fullPath: '/idcard-drivers'
      preLoaderRoute: typeof IdcardDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idcard-designer': {
      id: '/idcard-designer'
      path: '/idcard-designer'
      fullPath: '/idcard-designer'
      preLoaderRoute: typeof IdcardDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id-cards': {
      id: '/id-cards'
      path: '/id-cards'
      fullPath: '/id-cards'
      preLoaderRoute: typeof IdCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-results': {
      id: '/exam-results'
      path: '/exam-results'
      fullPath: '/exam-results'
      preLoaderRoute: typeof ExamResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline': {
      id: '/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-loans-history': {
      id: '/book-loans-history'
      path: '/book-loans-history'
      fullPath: '/book-loans-history'
      preLoaderRoute: typeof BookLoansHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-loans': {
      id: '/book-loans'
      path: '/book-loans'
      fullPath: '/book-loans'
      preLoaderRoute: typeof BookLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-years': {
      id: '/academic-years'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AcademicYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicYearsRoute: AcademicYearsRoute,
  AccountingRoute: AccountingRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  BookLoansRoute: BookLoansRoute,
  BookLoansHistoryRoute: BookLoansHistoryRoute,
  ClassesRoute: ClassesRoute,
  DisciplineRoute: DisciplineRoute,
  DiscountsRoute: DiscountsRoute,
  EventsRoute: EventsRoute,
  ExamResultsRoute: ExamResultsRoute,
  ExamsRoute: ExamsRoute,
  ExpensesRoute: ExpensesRoute,
  HealthRoute: HealthRoute,
  IdCardsRoute: IdCardsRoute,
  IdcardDesignerRoute: IdcardDesignerRoute,
  IdcardDriversRoute: IdcardDriversRoute,
  IdcardStaffRoute: IdcardStaffRoute,
  IdcardStudentsRoute: IdcardStudentsRoute,
  LibraryBooksRoute: LibraryBooksRoute,
  ParentsRoute: ParentsRoute,
  PaymentsRoute: PaymentsRoute,
  ReportCardsRoute: ReportCardsRoute,
  RevenueRoute: RevenueRoute,
  SalaryPaymentsRoute: SalaryPaymentsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StaffPointsRoute: StaffPointsRoute,
  StudentListRoute: StudentListRoute,
  StudentParentsRoute: StudentParentsRoute,
  StudentsRoute: StudentsRoute,
  SubjectsRoute: SubjectsRoute,
  TeachersRoute: TeachersRoute,
  TransportListRoute: TransportListRoute,
  TransportRoutesRoute: TransportRoutesRoute,
  UniformsRoute: UniformsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
